// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.5
// source: Chat/chat.proto

package Chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	SendMessage(ctx context.Context, opts ...grpc.CallOption) (Message_SendMessageClient, error)
	RecieveMessage(ctx context.Context, in *RecieveMessageRequest, opts ...grpc.CallOption) (Message_RecieveMessageClient, error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (Message_ChatClient, error)
}

type messageClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageClient(cc grpc.ClientConnInterface) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/Chat.Message/register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) SendMessage(ctx context.Context, opts ...grpc.CallOption) (Message_SendMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &Message_ServiceDesc.Streams[0], "/Chat.Message/sendMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageSendMessageClient{stream}
	return x, nil
}

type Message_SendMessageClient interface {
	Send(*SendMessageRequest) error
	CloseAndRecv() (*SendMessageResponse, error)
	grpc.ClientStream
}

type messageSendMessageClient struct {
	grpc.ClientStream
}

func (x *messageSendMessageClient) Send(m *SendMessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageSendMessageClient) CloseAndRecv() (*SendMessageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendMessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageClient) RecieveMessage(ctx context.Context, in *RecieveMessageRequest, opts ...grpc.CallOption) (Message_RecieveMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &Message_ServiceDesc.Streams[1], "/Chat.Message/recieveMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageRecieveMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Message_RecieveMessageClient interface {
	Recv() (*RecieveMessageResponse, error)
	grpc.ClientStream
}

type messageRecieveMessageClient struct {
	grpc.ClientStream
}

func (x *messageRecieveMessageClient) Recv() (*RecieveMessageResponse, error) {
	m := new(RecieveMessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageClient) Chat(ctx context.Context, opts ...grpc.CallOption) (Message_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &Message_ServiceDesc.Streams[2], "/Chat.Message/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageChatClient{stream}
	return x, nil
}

type Message_ChatClient interface {
	Send(*ChatRequest) error
	Recv() (*ChatResponse, error)
	grpc.ClientStream
}

type messageChatClient struct {
	grpc.ClientStream
}

func (x *messageChatClient) Send(m *ChatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageChatClient) Recv() (*ChatResponse, error) {
	m := new(ChatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageServer is the server API for Message service.
// All implementations must embed UnimplementedMessageServer
// for forward compatibility
type MessageServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	SendMessage(Message_SendMessageServer) error
	RecieveMessage(*RecieveMessageRequest, Message_RecieveMessageServer) error
	Chat(Message_ChatServer) error
	mustEmbedUnimplementedMessageServer()
}

// UnimplementedMessageServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServer struct {
}

func (UnimplementedMessageServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedMessageServer) SendMessage(Message_SendMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageServer) RecieveMessage(*RecieveMessageRequest, Message_RecieveMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method RecieveMessage not implemented")
}
func (UnimplementedMessageServer) Chat(Message_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedMessageServer) mustEmbedUnimplementedMessageServer() {}

// UnsafeMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServer will
// result in compilation errors.
type UnsafeMessageServer interface {
	mustEmbedUnimplementedMessageServer()
}

func RegisterMessageServer(s grpc.ServiceRegistrar, srv MessageServer) {
	s.RegisterService(&Message_ServiceDesc, srv)
}

func _Message_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chat.Message/register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_SendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServer).SendMessage(&messageSendMessageServer{stream})
}

type Message_SendMessageServer interface {
	SendAndClose(*SendMessageResponse) error
	Recv() (*SendMessageRequest, error)
	grpc.ServerStream
}

type messageSendMessageServer struct {
	grpc.ServerStream
}

func (x *messageSendMessageServer) SendAndClose(m *SendMessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageSendMessageServer) Recv() (*SendMessageRequest, error) {
	m := new(SendMessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Message_RecieveMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RecieveMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageServer).RecieveMessage(m, &messageRecieveMessageServer{stream})
}

type Message_RecieveMessageServer interface {
	Send(*RecieveMessageResponse) error
	grpc.ServerStream
}

type messageRecieveMessageServer struct {
	grpc.ServerStream
}

func (x *messageRecieveMessageServer) Send(m *RecieveMessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Message_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServer).Chat(&messageChatServer{stream})
}

type Message_ChatServer interface {
	Send(*ChatResponse) error
	Recv() (*ChatRequest, error)
	grpc.ServerStream
}

type messageChatServer struct {
	grpc.ServerStream
}

func (x *messageChatServer) Send(m *ChatResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageChatServer) Recv() (*ChatRequest, error) {
	m := new(ChatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Message_ServiceDesc is the grpc.ServiceDesc for Message service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Message_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Chat.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "register",
			Handler:    _Message_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "sendMessage",
			Handler:       _Message_SendMessage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "recieveMessage",
			Handler:       _Message_RecieveMessage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _Message_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Chat/chat.proto",
}
